server.port=9000

spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=personas
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/personas/**

spring.cloud.gateway.routes[1].id=finanzas
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/finanzas/**

spring.cloud.gateway.routes[2].id=familia
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/familia/**

spring.cloud.gateway.routes[3].id=acceso
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/acceso/**

spring.cloud.gateway.routes[4].id=fichasocial
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/fichasocial/**

spring.cloud.gateway.routes[5].id=bienes
spring.cloud.gateway.routes[5].uri=http://localhost:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/bienes/**

spring.cloud.gateway.routes[6].id=defunciones
spring.cloud.gateway.routes[6].uri=http://localhost:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/defunciones/**

spring.cloud.gateway.routes[7].id=documentos
spring.cloud.gateway.routes[7].uri=http://localhost:8088
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/documentos/**

spring.cloud.gateway.routes[8].id=beneficios
spring.cloud.gateway.routes[8].uri=http://localhost:8092
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/beneficios/**

spring.cloud.gateway.routes[9].id=deudas
spring.cloud.gateway.routes[9].uri=http://localhost:8093
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/deudas/** 